### ISSUE TITLE
How to Test data?

### ISSUE THREAD

**Issue by NightFury10497** [philipperemy/deep-speaker#24]
How can i Test data from these files of the branch Improvements one?

**Comment by WIll-Xu35** [comment]
I don't think you can run inference under the v3 repository since the author hasn't finished training according to the readme file. So there is no pretrained model released for inference. You might train it yourself before testing it if you have enough computational power. If you tried to train it yourself, please let us know how it goes.

**Comment by philipperemy** [comment]
@NightFury10497 @WIll-Xu35 yeah I still struggle to find time to work on it. I'm going to work on it now.

**Comment by WIll-Xu35** [comment]
@philipperemy Great!

One more thing to mention, is it possible to avoid using cache during inference and training? I understand using cache will speedup the process but when using large datasets, it is not possible to place the whole dataset into the cache. And personally I'm not familiar with cache operations and using cache make it very hard for me to modify the code and test on large scale dataset.

Thank you so much for your awesome work!

**Comment by philipperemy** [comment]
@NightFury10497 @WIll-Xu35 Try again with the new master. I pushed the latest code. Work is finally finished :) I uploaded the pre-trained H5 models and everything.
